name: RShil
favicon: null
layout_spectrum: 0.6870345624629408
typography_spectrum: 0.07883000769652426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5955840800888836
  lightness: 0.07458585151471198
  saturation: 0.057064859895035625
  rhythmicContrast: 0.5431899949908257
purpose: []
