name: RShil
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8faf7'
    - '#100f15'
    - '#c4b7a8'
    - '#765554'
    - '#a88d83'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
